services:
  app:
    image: ${IMAGE_NAME}
    environment:
      POSTGRES_CONN: ${POSTGRES_CONN}
      RANDOM_SECRET: ${RANDOM_SECRET}
      REDIS_CONN: "redis:6380"
      CAPTCHA_TOKEN: ${CAPTCHA_TOKEN}
      SMTP_PASS: ${SMTP_PASS}

    volumes:
      -  /home/tiver211/mods/mods.zip:/api/static/mods.zip

    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/tiver211/certs/bezmetejnost-ru/fullchain.pem:/etc/ssl/certs/cert.pem
      - /home/tiver211/certs/bezmetejnost-ru/private.key:/etc/ssl/certs/private.key
    depends_on:
      - app

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data
    command: ["redis-server", "--port", "6380"]

volumes:
  redis_data:
  postgres_data: