"""empty message

Revision ID: 305abdb0ddde
Revises: 
Create Date: 2025-05-27 07:32:39.073004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '305abdb0ddde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('alts_ip_key'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('alts', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('alts_ip_key'), ['ip'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
